version: '3'
services:
    bot:
        build: .
        env_file: .env
        environment:
            - REDIS_HOST=redis
        depends_on:
            - redis
        restart: unless-stopped
        volumes:
            - quran_data:/app/cogs/data
            - ./logs:/app/logs
        logging:
            driver: json-file
            options:
                max-size: "10m"
                max-file: "5"

    redis:
        image: redis/redis-stack-server:latest
        volumes:
            - ./config/redis.conf:/redis.conf:ro
            - redis_data:/data
        command: [ "redis-stack-server", "/redis.conf" ]
        restart: unless-stopped

volumes:
    redis_data:
    quran_data:
